title: Elena's Portfolio
logo:
paginate: 5
description: |-
  Hi! I am an italian girl, currently living in Denmark, and I am passionate about science and nature.<br />
  
  I have been a Visiting Student at Los Alamos National Laboratory and I have been part of CMCC,
  working on maritime weather forecast. I am currently a software engineer for wind turbines.
theme: jekyll-theme-minimal
plugins:
- jekyll-seo-tag
- jekyll-paginate
categories: [papers, projects]
